### PR TITLE
Upgrade Ember to 3.5

### PR DESCRIPTION
**Pull request by synaptiko**
Hello,

we are using your addon and we started having deprecations because of old version of ember-cli-babel. I attempted to upgrade this addon to the newest Ember. All codemods were run and everything looks correct, tests are running after few changes (removal of jquery and renaming attrs to options, for example).

### CODE REVIEW

**Review by walter — CHANGES_REQUESTED** [review]
Excellent! Thanks for modernizing this! Glad to hear someone still finds it useful.

The only thing I'm unsure of is if the README needs tweaking. Could you review it and add any needed changes and/or comment here on it it needs any.

**Comment by synaptiko** [comment]
I have updated README: https://github.com/walter/ember-cli-meta-options/pull/4/commits/296fbc5dfb0f0725958cc9726df2939b4bb3c840

I fixed two typos and switched `npm install` -> `ember install`.

If it's fine by you I think this is ready :-) I already use the upgraded fork in our app and seems to be ok so far.

**Comment by synaptiko** [comment]
Also I'm thinking how version should be changed. The functionality itself didn't change at all. But I think it's probably major version change. What do you think?

**Comment by walter** [comment]
> Also I'm thinking how version should be changed. The functionality itself didn't change at all. But I think it's probably major version change. What do you think?

Yeah, I agree. So `1.0` or `2.0`? What do you think? Feel free to update `package.json` in a commit on this PR.

**Review by walter — APPROVED** [review]

**Comment by walter** [comment]
Also could you add yourself as a contributor of the major upgrade under credits please.

**Comment by synaptiko** [comment]
Version bumped to 1.0 and credits section updated as well :-)

**Comment by walter** [comment]
Excellent! Thanks for all your help. Will now see about publishing the release. Been awhile!

**Comment by walter** [comment]
Published. Thanks for all your help.

**Pull request merged**
